name: Main
on:
  push:
    branches-ignore:
      - 'releases/**'
    paths-ignore:
      - '**.md'
      - '.github/workflows/release.yml'
      - '.gitignore'
      - 'crowdin.yml'
      - 'data/translations/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/release.yml'
      - '.gitignore'
      - 'crowdin.yml'
      - 'data/translations/**'
jobs:
  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Check formatting
        uses: DoozyX/clang-format-lint-action@v0.12
        with:
          clangFormatVersion: 12

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install apt packages
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install extra-cmake-modules libqt5x11extras5-dev qttools5-dev libkf5notifications-dev libkf5iconthemes-dev ninja-build

      # See https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4766#note_1091927
      - name: Downgrade CMake
        if: runner.os == 'Windows'
        uses: lukka/get-cmake@v3.21.2

      - name: Build without Plasma feature
        run: |
          cmake -B build -G Ninja -D CMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror"
          cmake --build build --parallel 2

      - name: Build with Plasma feature
        run: |
          cmake -B build -G Ninja -D WITH_PLASMA=ON -D CMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror"
          cmake --build build --parallel 2
